[package]
name = "speculare-pgcdc"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
log = "0.4"
openssl = "0.10"
postgres-protocol = { git = "https://github.com/Martichou/rust-postgres", branch = "replication" }
tokio-postgres = { git = "https://github.com/Martichou/rust-postgres", branch = "replication" }
tokio = "1"

[dependencies.actix-web]
git = "https://github.com/actix/actix-web"
tag = "web-v4.0.0-beta.1"
features = ["openssl"]