[package]
name = "speculare-pgcdc"
version = "0.0.5"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
ahash = "0.7"
async-trait = "0.1"
bytes = "1"
byteorder = "1.4"
clap = { version = "3.1", features = ["derive"] }
clap-verbosity-flag = "1.0"
config = "0.12"
env_logger = "0.9"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
openssl = "0.10"
postgres-openssl = { git = "https://github.com/Martichou/rust-postgres", branch = "copy-both" }
postgres-protocol = { git = "https://github.com/Martichou/rust-postgres", branch = "copy-both" }
serde = "1.0"
serde_json = "1.0"
simd-json = "0.4"
snmalloc-rs = "0.2"
tokio-postgres = { git = "https://github.com/Martichou/rust-postgres", branch = "copy-both" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
uuid-readable-rs = "0.1"
warp = { version = "0.3", features = ["tls"] }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1