[package]
name = "speculare-pgcdc"
version = "0.0.5"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-trait = "0.1"
bytes = "1"
byteorder = "1.4"
config = "0.11"
env_logger = "0.9"
futures = "0.3"
lazy_static = "1.4"
log = "0.4"
openssl = "0.10"
postgres-openssl = { git = "https://github.com/Martichou/rust-postgres", branch = "copy-both" }
postgres-protocol = { git = "https://github.com/Martichou/rust-postgres", branch = "copy-both" }
serde = "1.0"
serde_json = "1.0"
simd-json = "0.4"
tokio-postgres = { git = "https://github.com/Martichou/rust-postgres", branch = "copy-both" }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
uuid-readable-rs = { git = "https://github.com/Martichou/uuid-readable-rs" }
warp = { git = "https://github.com/seanmonstar/warp", features = ["tls"], rev = "985587a" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1