[package]
name = "speculare-pgcdc"
version = "0.1.0"
authors = ["Martichou <martichou.andre@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.11.0-beta.2"
actix-web = { version = "4.0.0-beta.3", features = ["openssl"] }
actix-http = { version = "3.0.0-beta.3", features = ["openssl"] }
actix-web-actors = { git = "https://github.com/actix/actix-web", tag = "web-v4.0.0-beta.3" }
dotenv = "0.15"
env_logger = "0.8"
futures = "0.3"
log = "0.4"
openssl = { version = "0.10", features = ["vendored"] }
postgres-protocol = { git = "https://github.com/Martichou/rust-postgres", branch = "replication" }
rand = "0.8"
serde = "1.0"
serde_json = "1.0"
tokio-postgres = { git = "https://github.com/Martichou/rust-postgres", branch = "replication" }
tokio = "1"