POSTGRES_HOST = "127.0.0.1"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "azertyuiop"
POSTGRES_DATABASE = "speculare"
POSTGRES_TLS = false			# default = true

BINDING = "0.0.0.0:8080"

KEY_PRIV = "key.pem"			# (optional)
KEY_CERT = "cert.pem"			# (optional)
HTTPS = true					# (optional [default = false])

RUST_LOG = "warn,speculare_pgcdc=info,warp=info"	# (optional)