name: CLIPPY

on:
  pull_request:
    types: [opened, synchronize, reopened]

name: Clippy and rustfmt Check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
      - name: Check with Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --all --tests